# El método de k-means
con el metodo  de kmeans se eligen por defecto de la mano del experto el numero de clusters deseados, 
para eliger los varicentros existen varias formas una es con el vq y el otro con el kmenas de scipy

In [10]:
import numpy as np
import matplotlib


In [3]:
data = np.random.random(90).reshape(30,3)
data

array([[0.58251367, 0.52538116, 0.89581432],
       [0.98440364, 0.96559195, 0.09534644],
       [0.94827351, 0.64748192, 0.50586588],
       [0.1820333 , 0.49265867, 0.85917353],
       [0.80133372, 0.27822196, 0.66053175],
       [0.29941307, 0.18101933, 0.76547575],
       [0.81037941, 0.13286841, 0.88888464],
       [0.42124666, 0.16731944, 0.13623687],
       [0.90608791, 0.1424297 , 0.00147799],
       [0.20909946, 0.9656625 , 0.24009559],
       [0.91165021, 0.71951921, 0.67073621],
       [0.2692227 , 0.45690025, 0.98999302],
       [0.39676987, 0.21522092, 0.7333076 ],
       [0.23445622, 0.53423724, 0.14606631],
       [0.00701295, 0.97180595, 0.17362036],
       [0.1445559 , 0.80333132, 0.07006532],
       [0.80088422, 0.1194784 , 0.36236534],
       [0.15257598, 0.08012909, 0.20683122],
       [0.72105493, 0.63597201, 0.94794365],
       [0.44966928, 0.54387504, 0.95606548],
       [0.13571164, 0.82093515, 0.38256116],
       [0.93322742, 0.02701827, 0.36703971],
       [0.

In [4]:
c1 = np.random.choice(range(len(data)))
c2 = np.random.choice(range(len(data)))
clust_centers = np.vstack([data[c1], data[c2]])#vstack coloca uno debajo de otro
clust_centers

array([[0.91165021, 0.71951921, 0.67073621],
       [0.15257598, 0.08012909, 0.20683122]])

In [1]:
#libreria para encontrar los varicentros y los 
from scipy.cluster.vq import vq


In [7]:
clusters = vq(data, clust_centers)
clusters

(array([0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0,
        0, 1, 0, 1, 1, 1, 1, 1]),
 array([0.44348686, 0.63001448, 0.18361063, 0.77239813, 0.45499134,
        0.5863648 , 0.63403759, 0.29115228, 0.78347402, 0.86000896,
        0.        , 0.76394157, 0.59586729, 0.46541482, 0.90409024,
        0.73606433, 0.66786436, 0.        , 0.34662755, 0.5706926 ,
        0.76155041, 0.75647517, 0.49716966, 0.91189836, 0.75860058,
        0.55552659, 0.71846421, 0.36201179, 0.5336934 , 0.51426722]))

In [8]:
labels = clusters[0]
labels

array([0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 1, 1, 1])

In [2]:
import plotly.plotly as py
import plotly.graph_objs as go
import plotly.offline as ply

ImportError: 
The plotly.plotly module is deprecated,
please install the chart-studio package and use the
chart_studio.plotly module instead. 


In [16]:
x = []
y = []
z = []
x2 = []
y2 = []
z2 = []

for i in range(0, len(labels)):
    if(labels[i] == 0):
        x.append(data[i,0])
        y.append(data[i,1])
        z.append(data[i,2])
        
    else:
        x2.append(data[i,0])
        y2.append(data[i,1])
        z2.append(data[i,2])

cluster1 = go.Scatter3d(
    x=x,
    y=y,
    z=z,
    mode='markers',
    marker=dict(
        size=12,
        line=dict(
            color='rgba(217, 217, 217, 0.14)',
            width=0.5
        ),
        opacity=0.9
    ),
    name="Cluster 0"
)


cluster2 = go.Scatter3d(
    x=x2,
    y=y2,
    z=z2,
    mode='markers',
    marker=dict(
        color='rgb(127, 127, 127)',
        size=12,
        symbol='circle',
        line=dict(
            color='rgb(204, 204, 204)',
            width=1
        ),
        opacity=0.9
    ),
    name="Cluster 1"
)
data2 = [cluster1, cluster2]
layout = go.Layout(
    margin=dict(
        l=0,
        r=0,
        b=0,
        t=30
    )
)

fig = go.Figure(data=data2, layout=layout)
ply.plot(fig, filename='Clusters')


NameError: name 'go' is not defined

In [17]:
from scipy.cluster.vq import kmeans

In [18]:
kmeans(data, clust_centers)

(array([[0.75208484, 0.38075695, 0.53111889],
        [0.17837722, 0.50507789, 0.44347637]]),
 0.46837335804545177)

In [19]:
kmeans(data, 2)#en esta se le da el numero k = numero de clusters deseados

(array([[0.55556667, 0.30961511, 0.58605931],
        [0.25037214, 0.86315061, 0.17531534]]),
 0.443214280524482)